### PR TITLE
removing redundant mkdir call

### PR DESCRIPTION
**Pull request by mohanksriram**

### CODE REVIEW

**Comment by ravisoni31** [comment]
The PR is also ready to merge.

**Comment by void-robotics** [comment]
According to the coding conventions, we shouldn't have 2 functions that do similar things:
Simulator::createSimFolder and GenUtil::createFilePath

Because creating folders is a general function and not specific to simulator, delete Simulator::createSimFolder

**Comment by mohanksriram** [comment]
Done

**Comment by ravisoni31** [comment]
This PR is ready to merge.

**Review by ghost — APPROVED** [review]

**Pull request merged**
