### PR TITLE
NEWMIND-140 docker parent image

### PR DESCRIPTION
**Pull request by wildomonges**
I've created Dockerfile and docker-build.sh files to run simulation using docker dependencies instead the local machine dependencies.

### CODE REVIEW

**Comment by ravisoni31** [comment]
Hi @wildomonges. Can you please go through the PR rules: https://github.com/nathangeorge1/newmind#-pr-rules? Thanks.

**Comment by wildomonges** [comment]
Hi @ravisoni31 , this is my first pull request, so maybe I did some mistakes. Rules here
The GitHub Manager will approve a PR or comment with changes within 48 hours of PR creation based on the following criteria:

have validations in JIRA -- 
What is the meaning of this?
pass all Jenkins tests (commenting in the PR the Jenkins build # if it passes)
Where I can run jenkis for my pull request?
meet the Coding Conventions
Well, I did not add any c++ code, so I am not sure what is wrong with that I've added.

**Comment by ravisoni31** [comment]
Hi @wildomonges, No issues. I understand. I just wanted to make sure that we go through the rules etc. from the first PR. I did not see the Jenkin build number so just wanted to let you know. I missed the fact that you are just starting off with Jenkins too. 

1. Have validations in JIRA -- 
It means that one should go through the validation section of the task and attach necessary documents. 
For e.g, you have two validation points

- Create a document outlining all steps from start to finish; then, explain to Nathan so he can understand
- run SimulatorNode.launch using Docker and no local system dependencies.

So you need to attach necessary docs for these two parts. I think you have attached something so I will go through it.

2. Oh, I think we need to create Jenkin login credentials for it. I will check with Nathan. You can also do that; he will create login etc and give it to you. Also, you just need to add the Jenkins build number. I will show you. 
3. Yes. You do not have any c++ code. So no issues there.

**Comment by ravisoni31** [comment]
Did you get access to Jenkins, @wildomonges ? And were you able to do part 2 of the validation? If yes, please let me know where to look for. Thanks.
 
Anyways, the Jenkins build number is **22** for this PR.

**Comment by wildomonges** [comment]
@ravisoni31  I will create the video for validation of this pull request. Also, @nathangeorge1  just give to me access to Jenkins. I will let you know when the video is done.

**Comment by wildomonges** [comment]
I've uploaded the video for validation of this pull request, also the documentations done for docker. Please see for issue reference https://newmind.atlassian.net/browse/NEWMIND-140.
Video and document were uploaded to Newmind Robotics/Technical Information/Software/Docker/ 
I am not sure how to build the project from Jenkins.

**Review by ghost — APPROVED** [review]

**Comment by void-robotics** [comment]
good work @wildomonges; there are a few changes needed but I'll create another task for them

**Pull request merged**
